name = "NeuralDELux"
uuid = "42edd903-6642-4dc2-93f6-9358071582bf"
authors = ["Maximilian Gelbrecht <maximilian.gelbrecht@posteo.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
